"""initial migration

Revision ID: 58b5b922622e
Revises: 7449b6de3ef9
Create Date: 2023-12-11 18:16:50.317325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58b5b922622e'
down_revision = '7449b6de3ef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_file', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
